# Generated by Django 4.2 on 2023-05-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='critical_receptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='liner_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='record_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='liner_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
