# Generated by Django 4.2 on 2023-05-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_track_lyrics_tracklike'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(blank=True, to='tracks.image'),
        ),
    ]
