# Generated by Django 4.2 on 2023-05-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_album_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_type',
            field=models.CharField(choices=[('art', 'Art'), ('logo', 'Logo')], default='art', max_length=10),
        ),
    ]
