# Generated by Django 4.2 on 2023-05-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0006_clip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.JSONField(),
        ),
    ]
